services:
  mariadb:
    image: mariadb:11.3
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: university
      MARIADB_USER: admin
      MARIADB_PASSWORD: adminpass
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: university
      DB_USER: admin
      DB_PASSWORD: adminpass
    depends_on:
      - mariadb

volumes:
  mariadb_data: