const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
  host: 'sandbox.smtp.mailtrap.io',
  port: 2525,
  auth: {
    user: '173e40d2c740e8',
    pass: '0bd85545226b82'
  }
});

async function sendEnrollmentConfirmation(to, studentName, courseName) {
  const info = await transporter.sendMail({
    from: '"University of Vienna" <noreply@univienna.edu>',
    to,
    subject: 'Enrollment Confirmation',
    text: `Hello ${studentName},\n\nYou have successfully enrolled in ${courseName}.`,
    html: `<p>Hello ${studentName},</p><p>You have successfully enrolled in <strong>${courseName}</strong>.</p>`
  });

  console.log('📬 Enrollment email sent:', info.messageId);
}

async function sendStudentCredentials(to, studentName, tempPassword) {
  const info = await transporter.sendMail({
    from: '"University of Vienna - Administration" <admin@univienna.edu>',
    to,
    subject: 'Your Student Account Has Been Created',
    text: `Dear ${studentName},

Welcome to the University of Vienna Student Enrollment System!

Your student account has been successfully created by our administrative staff. Below are your login credentials:

Email: ${to}
Temporary Password: ${tempPassword}

IMPORTANT SECURITY NOTICE:
- This is a temporary password generated by our system
- Please log in and change your password immediately
- Keep your credentials secure and do not share them with anyone

You can access the system at: [University Login Portal]

If you have any questions or need assistance, please contact our student support team.

Best regards,
University of Vienna Administration`,
    html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <div style="background: linear-gradient(135deg, #4e54c8, #8f94fb); color: white; padding: 20px; text-align: center;">
                <h2>Welcome to University of Vienna</h2>
                <p>Student Enrollment System</p>
            </div>
            
            <div style="padding: 30px; background-color: #f9f9f9;">
                <h3>Dear ${studentName},</h3>
                
                <p>Your student account has been successfully created by our administrative staff.</p>
                
                <div style="background-color: white; border-left: 4px solid #4e54c8; padding: 20px; margin: 20px 0;">
                    <h4>Your Login Credentials:</h4>
                    <p><strong>Email:</strong> ${to}</p>
                    <p><strong>Temporary Password:</strong> <code style="background-color: #f0f0f0; padding: 2px 6px; border-radius: 3px;">${tempPassword}</code></p>
                </div>
                
                <div style="background-color: #fff3cd; border: 1px solid #ffeaa7; padding: 15px; border-radius: 5px; margin: 20px 0;">
                    <h4 style="color: #856404;">🔒 Important Security Notice:</h4>
                    <ul style="color: #856404; margin: 0;">
                        <li>This is a temporary password generated by our system</li>
                        <li>Please log in and change your password immediately</li>
                        <li>Keep your credentials secure and do not share them</li>
                    </ul>
                </div>
                
                <div style="text-align: center; margin: 30px 0;">
                    <a href="#" style="background-color: #4e54c8; color: white; padding: 12px 25px; text-decoration: none; border-radius: 5px; display: inline-block;">Access Student Portal</a>
                </div>
                
                <p>If you have any questions or need assistance, please contact our student support team.</p>
                
                <p>Best regards,<br>
                <strong>University of Vienna Administration</strong></p>
            </div>
            
            <div style="background-color: #e9ecef; padding: 15px; text-align: center; font-size: 12px; color: #6c757d;">
                <p>This is an automated message. Please do not reply to this email.</p>
            </div>
        </div>`
  });

  console.log('📬 Student credentials email sent:', info.messageId);
}

module.exports = { sendEnrollmentConfirmation, sendStudentCredentials };